In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
import requests
import json
from pathlib import Path
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from collections import Counter
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from collections import Counter
from imblearn.over_sampling import RandomOverSampler

In [2]:
data = Path('./results/DataProcessingExtractFile-RawData.csv')
df = pd.read_csv(data)
df.head(10)

,Diabetes_Status,HighBP,HighChol,CholCheck,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,Mental_Health_Range,Physical_Health_Range,DiffWalk,Sex,Age,Education,Income
0,1,1.0,1.0,1.0,4,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,4,3,1.0,0.0,9.0,4.0,3.0
1,1,0.0,0.0,0.0,3,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,1,1,0.0,0.0,7.0,6.0,1.0
2,1,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,6,6,1.0,0.0,9.0,4.0,8.0
3,1,1.0,0.0,1.0,3,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,3.0,6.0
4,1,1.0,1.0,1.0,2,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,5.0,4.0
5,1,1.0,1.0,1.0,3,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,1.0,10.0,6.0,8.0
6,1,1.0,0.0,1.0,4,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,1,3,0.0,0.0,9.0,6.0,7.0
7,1,1.0,1.0,1.0,3,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,1,1,1.0,0.0,11.0,4.0,4.0
8,2,1.0,1.0,1.0,4,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,6,6,1.0,0.0,9.0,5.0,1.0
9,1,0.0,0.0,1.0,2,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,1,1,0.0,1.0,8.0,4.0,3.0

In [3]:
# K Nearest Neighbors Model

X = df.copy()
X = df.drop(df.columns[[0]], axis=1)
X.head()

,HighBP,HighChol,CholCheck,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,Mental_Health_Range,Physical_Health_Range,DiffWalk,Sex,Age,Education,Income
0,1.0,1.0,1.0,4,1.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,4,3,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,3,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,3.0,1,1,0.0,0.0,7.0,6.0,1.0
2,1.0,1.0,1.0,3,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,5.0,6,6,1.0,0.0,9.0,4.0,8.0
3,1.0,0.0,1.0,3,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,3.0,6.0
4,1.0,1.0,1.0,2,0.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,11.0,5.0,4.0

In [4]:
y = df["Diabetes_Status"].ravel()
y[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1])

In [5]:
# MLP networks are sensitive to unscaled data
# this data is all categorical, scaled converges faster, but gives worse results
#sc = StandardScaler()
#scaler = sc.fit(X)

In [6]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    random_state=78,
                                                    stratify=y)
#X_train = scaler.transform(X_train)
#X_test = scaler.transform(X_test)
#X_train[:3]
X_train.head(3)

,HighBP,HighChol,CholCheck,BMI_Range,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,...,AnyHealthcare,NoDocbcCost,GenHlth,Mental_Health_Range,Physical_Health_Range,DiffWalk,Sex,Age,Education,Income
173928,1.0,0.0,1.0,4,0.0,1.0,0.0,1.0,1.0,1.0,...,1.0,0.0,3.0,1,1,0.0,0.0,11.0,3.0,7.0
239730,0.0,1.0,1.0,3,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,5.0,2,1,1.0,0.0,7.0,3.0,4.0
81199,0.0,1.0,1.0,2,0.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,1,1,0.0,0.0,6.0,6.0,8.0

In [7]:
print('y_train dataset shape {}'.format(Counter(y_train)))

y_train dataset shape Counter({1: 160277, 2: 29983})

In [8]:
# make a balanced dataset before training
ros = RandomOverSampler(random_state=78)
X_res, y_res = ros.fit_resample(X_train, y_train)
print('Resampled dataset shape {}'.format(Counter(y_res)))

Resampled dataset shape Counter({1: 160277, 2: 160277})

In [9]:
# uncomment to revert oversampling as a test
#X_res=X_train
#y_res=y_train

In [10]:
# Create a Neural Net classifier.
mlp_model = MLPClassifier(random_state=78, verbose=True, max_iter=300,
                          hidden_layer_sizes=(64,8), 
                          solver="adam", activation="relu")

In [11]:
# Fitting the model
mlp_model = mlp_model.fit(X_res, y_res)

Iteration 1, loss = 0.53321674
Iteration 2, loss = 0.51993002
Iteration 3, loss = 0.51741493
Iteration 4, loss = 0.51625158
Iteration 5, loss = 0.51476033
Iteration 6, loss = 0.51394716
Iteration 7, loss = 0.51349436
Iteration 8, loss = 0.51305059
Iteration 9, loss = 0.51255999
Iteration 10, loss = 0.51207980
Iteration 11, loss = 0.51156245
Iteration 12, loss = 0.51131691
Iteration 13, loss = 0.51108776
Iteration 14, loss = 0.51065163
Iteration 15, loss = 0.51027765
Iteration 16, loss = 0.50993151
Iteration 17, loss = 0.50970734
Iteration 18, loss = 0.50941197
Iteration 19, loss = 0.50918640
Iteration 20, loss = 0.50865686
Iteration 21, loss = 0.50861662
Iteration 22, loss = 0.50782393
Iteration 23, loss = 0.50775194
Iteration 24, loss = 0.50754639
Iteration 25, loss = 0.50700819
Iteration 26, loss = 0.50693921
Iteration 27, loss = 0.50685300
Iteration 28, loss = 0.50631461
Iteration 29, loss = 0.50629142
Iteration 30, loss = 0.50598226
Iteration 31, loss = 0.50588222
Iteration 32, loss = 0.50597317
Iteration 33, loss = 0.50551706
Iteration 34, loss = 0.50527144
Iteration 35, loss = 0.50516473
Iteration 36, loss = 0.50485914
Iteration 37, loss = 0.50477186
Iteration 38, loss = 0.50469476
Iteration 39, loss = 0.50441067
Iteration 40, loss = 0.50420811
Iteration 41, loss = 0.50426779
Iteration 42, loss = 0.50405245
Iteration 43, loss = 0.50386913
Iteration 44, loss = 0.50376511
Iteration 45, loss = 0.50364576
Iteration 46, loss = 0.50362087
Iteration 47, loss = 0.50330453
Iteration 48, loss = 0.50308441
Iteration 49, loss = 0.50304502
Iteration 50, loss = 0.50294216
Iteration 51, loss = 0.50275742
Iteration 52, loss = 0.50281639
Iteration 53, loss = 0.50267876
Iteration 54, loss = 0.50255362
Iteration 55, loss = 0.50271977
Iteration 56, loss = 0.50230043
Iteration 57, loss = 0.50209732
Iteration 58, loss = 0.50192900
Iteration 59, loss = 0.50219409
Iteration 60, loss = 0.50166508
Iteration 61, loss = 0.50180768
Iteration 62, loss = 0.50172502
Iteration 63, loss = 0.50163111
Iteration 64, loss = 0.50151451
Iteration 65, loss = 0.50140063
Iteration 66, loss = 0.50120156
Iteration 67, loss = 0.50125203
Iteration 68, loss = 0.50133810
Iteration 69, loss = 0.50117518
Iteration 70, loss = 0.50110768
Iteration 71, loss = 0.50106639
Iteration 72, loss = 0.50074273
Iteration 73, loss = 0.50083675
Iteration 74, loss = 0.50058290
Iteration 75, loss = 0.50058468
Iteration 76, loss = 0.50054958
Iteration 77, loss = 0.50070485
Iteration 78, loss = 0.50039409
Iteration 79, loss = 0.50039309
Iteration 80, loss = 0.50032863
Iteration 81, loss = 0.50017303
Iteration 82, loss = 0.50034362
Iteration 83, loss = 0.49998002
Iteration 84, loss = 0.50006919
Iteration 85, loss = 0.49998079
Iteration 86, loss = 0.49992764
Iteration 87, loss = 0.49986691
Iteration 88, loss = 0.49986797
Iteration 89, loss = 0.49967067
Iteration 90, loss = 0.49983178
Iteration 91, loss = 0.49968599
Iteration 92, loss = 0.49960472
Iteration 93, loss = 0.49957304
Iteration 94, loss = 0.49954135
Iteration 95, loss = 0.49954955
Iteration 96, loss = 0.49939107
Iteration 97, loss = 0.49942401
Iteration 98, loss = 0.49926026
Iteration 99, loss = 0.49902821
Iteration 100, loss = 0.49915813
Iteration 101, loss = 0.49900104
Iteration 102, loss = 0.49902755
Iteration 103, loss = 0.49889882
Iteration 104, loss = 0.49909487
Iteration 105, loss = 0.49884461
Iteration 106, loss = 0.49893328
Iteration 107, loss = 0.49868855
Iteration 108, loss = 0.49877078
Iteration 109, loss = 0.49876177
Iteration 110, loss = 0.49858489
Iteration 111, loss = 0.49844023
Iteration 112, loss = 0.49865473
Iteration 113, loss = 0.49830987
Iteration 114, loss = 0.49836493
Iteration 115, loss = 0.49838711
Iteration 116, loss = 0.49820050
Iteration 117, loss = 0.49817845
Iteration 118, loss = 0.49819436
Iteration 119, loss = 0.49831100
Iteration 120, loss = 0.49804370
Iteration 121, loss = 0.49835392
Iteration 122, loss = 0.49837167
Iteration 123, loss = 0.49817075
Iteration 124, loss = 0.49811826
Iteration 125, loss = 0.49804954
Iteration 126, loss = 0.49785762
Iteration 127, loss = 0.49796186
Iteration 128, loss = 0.49781297
Iteration 129, loss = 0.49806937
Iteration 130, loss = 0.49787896
Iteration 131, loss = 0.49767275
Iteration 132, loss = 0.49778929
Iteration 133, loss = 0.49772249
Iteration 134, loss = 0.49765990
Iteration 135, loss = 0.49764650
Iteration 136, loss = 0.49761134
Iteration 137, loss = 0.49793538
Iteration 138, loss = 0.49771594
Iteration 139, loss = 0.49764915
Iteration 140, loss = 0.49736457
Iteration 141, loss = 0.49762463
Iteration 142, loss = 0.49773040
Iteration 143, loss = 0.49741089
Iteration 144, loss = 0.49735983
Iteration 145, loss = 0.49732951
Iteration 146, loss = 0.49730882
Iteration 147, loss = 0.49729230
Iteration 148, loss = 0.49724322
Iteration 149, loss = 0.49740924
Iteration 150, loss = 0.49738171
Iteration 151, loss = 0.49728315
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [12]:
# evaluate the training accuracy first, based on the data before oversampling
pred_train=mlp_model.predict(X_train)
cm_train = confusion_matrix(y_train, pred_train)
cmt_df = pd.DataFrame(
    cm_train, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cmt_df

          Predicted 0  Predicted 1
Actual 0       116621        43656
Actual 1         6589        23394

In [13]:
# Calculate the accuracy score on trained set.
acc_score = accuracy_score(y_train, pred_train)
acc_score

0.7359140124040786

In [14]:
# Making predictions using the testing data.
predictions = mlp_model.predict(X_test)
predictions

array([1, 2, 1, ..., 2, 2, 1])

In [15]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

cm_df

          Predicted 0  Predicted 1
Actual 0        38613        14813
Actual 1         2429         7565

In [16]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)
acc_score

0.7281299274676758

In [17]:
# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0        38613        14813
Actual 1         2429         7565

Accuracy Score : 0.7281299274676758
Classification Report
              precision    recall  f1-score   support

           1       0.94      0.72      0.82     53426
           2       0.34      0.76      0.47      9994

    accuracy                           0.73     63420
   macro avg       0.64      0.74      0.64     63420
weighted avg       0.85      0.73      0.76     63420

In [18]:
pickle.dump(mlp_model, open('mlp_model.pkl','wb'))